CURSE/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import aboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', aboutView ),
    path('', include('ResourceLibrary.urls')),
    
    path('accounts/', include('allauth.urls')),
]

ResourceLibrary/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.EntryList.as_view(), name='home'),
    # path('<slug:slug>/', views.EntryDetail.as_view(), name='entry_detail'),
    path('search/', views.SearchResultsView.as_view(), name="search_results"),
    path('<slug:slug>/', views.entry_detail, name='entry_detail'),
    
]

ResourceLibrary/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# from django.contrib.auth import get_user_model

# SUBJECTS = (
#     (0,"Maths"),
#     (1,"Physics"),
#     (2,"Global Perspectives"),
#     (3, "Computer Science")

# )
RESTYPE = (
    (0,"Detailed Notes"),
    (1,"Tools"),
    (2,"Revision Notes"),
    (3,"Formula Sheets"),
    (4,"Concept Clarification"),
    (5,"Other"),
)

class Subject(models.Model):
    name = models.CharField(max_length =50)
    def __str__(self):
        return self.name

class Level(models.Model):
    name = models.CharField(max_length =50)
    def __str__(self):
        return self.name

class Entry(models.Model):
    name = models.CharField(max_length=100, unique=True)
    author = models.ForeignKey(User, on_delete= models.SET("Deleted User"),related_name='resource_entries')
    description = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    restype = models.IntegerField(choices=RESTYPE, default=0)
    subject = models.ForeignKey(Subject, on_delete=models.PROTECT)
    level = models.ForeignKey(Level, on_delete=models.PROTECT)

    resourcelink = models.URLField(("ResourceURLs"), max_length=1000, null=True,blank=True)
    embedlink = models.URLField(("VideoURLs"), max_length=1000, null=True, blank=True)
    affiliateflag = models.BooleanField(("Paid Promotion"),default=False)
    customhtml = models.TextField(("Custom HTML Code"),blank=True, null=True)
    extracontrib = models.CharField(("Extra Contributor Credits"),max_length=100, blank=True, null=True)



    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name
    

class Comment(models.Model):
    entry = models.ForeignKey(Entry,on_delete=models.CASCADE,related_name='comments')
    name = models.TextField(max_length=50)
    email = models.TextField(max_length=50)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']
        
    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

ResourceLibrary/forms.py
from .models import Comment
from django import forms



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {
            'body': 'Comment:',
        }

CURSE/views.py
from django.http import HttpResponse
from django.shortcuts import render

def aboutView(request):
    return render(request, "about.html")

ResourceLibrary/views.py
from django.views import generic
from .models import Entry
from django.contrib.auth.models import User
from .forms import CommentForm
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q


# class EntryListSearch(generic.ListView):
#     queryset = Entry.objects.order_by('-restype')
#     template_name = 'search_results.html'

class EntryList(generic.ListView):
    queryset = Entry.objects.order_by('-restype')
    template_name = 'library.html'

class EntryDetail(generic.DetailView):
    model = Entry
    template_name = 'entry_detail.html'

# class SearchResultsView(generic.ListView):
#     model = Entry
#     template_name = 'search_results.html'

class SearchResultsView(generic.ListView):
    model = Entry
    template_name = "search_results.html"

    def get_queryset(self):  # new
        query = self.request.GET.get("q")
        object_list = Entry.objects.filter(
            Q(name__icontains=query)  | Q(description__icontains=query) 
        )
        return object_list

# @login_required
def entry_detail(request, slug):
    template_name = 'entry_detail.html'
    entry = get_object_or_404(Entry, slug=slug)
    comments = entry.comments.filter(active=True)
    new_comment = None
    # user = User.get_username(User)
    # user_email = User.objects.get()
    # Comment posted
    if request.method == 'POST' and request.user.is_authenticated:
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.entry = entry
            new_comment.name = request.user
            new_comment.email = request.user.email
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'entry': entry,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

templates/about.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>

<body>
    <style>
        .maindiv {
            display: flex;
            flex-direction: row;
        }

        .maindiv p {
            padding: 0 auto;
        }

        #textmain {
            width: fit-content;
            height: min-content;
            /* white-space: 50%; */
            /* line-height: 95%; */
            font-size: smaller;
        }

        .card {
            width: 17em;
            padding: 0.5rem;
            /* margin-right: 2rem; */
            height: 22.5em;
            background: #FBCA1F;
            transition: 1s ease-in-out;
            clip-path: polygon(30px 0%, 100% 0, 100% calc(100% - 30px), calc(100% - 30px) 100%, 0 100%, 0% 30px);
            /* border-top-right-radius: 20px; */
            /* border-bottom-left-radius: 20px; */
            display: flex;
            flex-direction: column;
            margin: 1rem 0.8rem;
            box-sizing: content-box;
        }

        .card span {
            font-weight: bold;
            color: rgb(0, 0, 0);
            text-align: center;
            display: block;
            font-size: 1em;
        
        }

        .card .info {
            font-weight: 400;
            color: rgb(0, 0, 0);
            display: block;
            text-align: center;
            font-size: 0.72em;
            margin: 1em;
        }

        .card .img {
            width: 4.8em;
            height: 4.8em;
            /* background: #303030; */
            border-radius: 15px;
            margin: auto;
            background-image: url("{% static 'img/khizar.jpg' %}") ;
            background-size: contain;
            /* z-index: 1; */
        }

        .card .share {
            margin-top: 1em;
            display: flex;
            justify-content: center;
            gap: 1em;
        }

        .card a {
            color: black;
            transition: .4s ease-in-out;
        }

        .card a:hover {
            color: rgb(0, 110, 255);
        }

        .card button {
            padding: 0.8em 1.7em;
            display: block;
            margin: auto;
            /* border-radius: 25px; */
            border: none;
            font-weight: bold;
            background: black;
            color: rgb(255, 255, 255);
            transition: .4s ease-in-out;
            clip-path: polygon(30px 0%, 100% 0, 100% calc(100% - 30px), calc(100% - 30px) 100%, 0 100%, 0% 30px);
        }

        .card button:hover {
            background: rgb(184, 171, 0);
            color: #000000;
            cursor: pointer;
        }

        @media(max-width:600px) {
            .maindiv {
            display: flex;
            flex-direction: column;
            
        }
        .card{
            width: auto;
        }


        }
    </style>
    <!-- <br> -->
    <hr>
    <div class="maindiv">
        <div id="textmain">
            <h2 class="paddedhead">CURSE? </h2>
            <p>Well, yes. As a student having no excuse to not being able to score higher is a real curse. Appropriately
                named,
                in my opinion.</p>
            <!-- <br> -->
            <p>On a more serious note, I always wished someone would show me the best way to learn difficult concepts in
                the
                best manner and what I couldn't have, I serve you. Hence I present, this collection of resources I found
                very
                useful as a Cambridge student. </p>
            <!-- <br> -->
            <p>I do wish to add more features in time, already working on a quiz generator engine... but for now this
                blog
                system should help out a little</p>

            <h4 class="paddedhead">Who am I?</h4>
            <p>My name is Khizar, I am 18 and have this ludicrous dream of revolutionizing the world one small step at a
                time.
            </p>
            <p> Wish me luck on this arduous journey.</p>
        </div>
        <div class="card">
            <div class="img"></div>
            <span>About Me</span>
            <p class="info">My name is Khizar and I am a hobbyist software developer who likes to do that one thing
                which very unnessecary but only slightly impractical.</p>
            <div class="share">
                <a href="https://github.com/Khizary/"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                        fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                        <path
                            d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z">
                        </path>
                    </svg></a>
                <a href=""><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-twitter" viewBox="0 0 16 16">
                        <path
                            d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z">
                        </path>
                    </svg></a>
                <a href="https://www.instagram.com/khizar.thinks/"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                        height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                        <path
                            d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z">
                        </path>
                    </svg></a>
                <a href=""><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-youtube" viewBox="0 0 16 16">
                        <path
                            d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z">
                        </path>
                    </svg></a>
            </div>
            <a href="mailto:khizarchuadry@gmail.com"><button>Email Me</button></a>
        </div>
    </div>
</body>

</html>
{% endblock content %}

templates/entry_detail.html
{% extends 'base.html' %}

{% block content %}
{% load filters %}
<style>

</style>
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <br>
        <h2 class="coolhead">{% block title %} {{ entry.name }} {% endblock title %}</h2>
        <p class="deet-text text-dark mb-0">{{ entry.subject }} | {{ entry.level}} </p>
        <p class="deet-text text-muted mb-0">{{ entry.author }} | {{ entry.created_on }}</p>
        {% if entry.affiliatetag == True %}
        <p class="deet-text text-muted mb-0">Paid Promotion</p>
        {% endif %}
        <hr>
        <p class="deet-text">{{ entry.description | safe }}</p>
        <!-- <p>{{entry.resourcelink}}</p> -->
        {% if entry.resourcelink != None %}
        {% with entry.resourcelink|split:"," as rslinks %}
        {% for item in rslinks %}
        <p><a id="hrefelem" href="{{ item }}" class="button" style="scale: 0.8;">Resource Link</a></p>
        {% endfor %}
        {% endwith %}
        {% endif %}

        {% if entry.embedlink != None %}
        {% with entry.embedlink|split:"," as emlinks %}
        {% for item in emlinks %}
        <p><iframe id="iframeelem" width="560" height="315" src="{{ item }}" title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture;"
            allowfullscreen></iframe></p>
        {% endfor %}
        {% endwith %}
        {% endif %}

        {% if entry.customhtml != None %}
        <p><div id="customcode">{{ entry.customhtml }}</div></p>
        {% endif %}

        {% if entry.extracontrib != None %}
        <p class="deet-text text-muted mb-0">Credits:&nbsp;{{ entry.extracontrib }}</p>
          <br>
        {% endif %}


        <br>
      </div>
    </div>


    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h5>{{ comments.count }} comments</h5>
        {% for comment in comments %}
        <div class="comments" style="padding: 10px; font-size: smaller;">
          <p class="font-weight-normal text-muted">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              &nbsp| {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation.
        </div>
        {% elif request.user.is_authenticated %}
        <h6>Leave a comment: </h6>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <!-- <label for="id_body">Comment:</label> -->
          <!-- <label for=""></label> -->
          <button type="submit" class="button" style="scale: 0.7;">Submit</button>
        </form>

        {% else %}
        <h6> Log in to leave a comment! </h6>
        <br>
        <a href="{% url 'account_login' %}?next={{ request.build_absolute_uri }}" class="button" >Login</a>.
        <!-- <button type="submit" class="button" style="scale: 0.7;">Submit</button> -->
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/library.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<style>
    body {
        font-family: 'mononoki', sans-serif;
        font-size: 1rem;
        background-color: #EFEFEF;
    }
</style>

<header class="masthead">
    <title>Library</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400&display=swap" rel="stylesheet">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> C.U.R.S.E Library </h3>
                    <p class="text-light">All the best educational resources at your disposal! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">

        <!-- Blog Entries Column -->
        <div id="postholder" class="col-md-10 mt-3 center">
            <br>
            <form action="{% url 'search_results' %}" method="get">
                <!-- <input id="searchbar" name="q" type="text" placeholder="Search..."> -->
            
            <div class="input-container">
                <input type="text" name="q" class="input" placeholder="search...">
                <button id="btnsrch"class="button"type="submit">
                <!-- <span class="icon">  -->
                  <svg width="19px" height="19px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path opacity="1" d="M14 5H20" stroke="#000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path> <path opacity="1" d="M14 8H17" stroke="#000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M21 11.5C21 16.75 16.75 21 11.5 21C6.25 21 2 16.75 2 11.5C2 6.25 6.25 2 11.5 2" stroke="#000" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"></path> <path opacity="1" d="M22 22L20 20" stroke="#000" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
                <!-- </span> -->
            </button>
              </div>
            </form>
            <br>
            {% for Entry in entry_list %}
            <div class="papper mb-4">
                <div class="card-body text-center">
                    <h2 class="card-title">{{ Entry.name|slice:":200" }}</h2>
                    <hr>
                    <p class="card-text text-muted h6">{{ Entry.author }} | {{ Entry.created_on}} </p>
                    <p class="card-text h6">{{ Entry.subject }} | {{ Entry.level}} </p>
                    <p class="card-text">{{Entry.get_restype_display}}</p>
                    <a href="{% url 'entry_detail' Entry.slug  %}" class="button">Read More &rarr;</a>

                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{%endblock%}

<!-- 
<input type="hidden" name="csrfmiddlewaretoken" value="rOFfeAy1CDIuw9twM2fXZBo6OzcDIBsqQmLZ28tbxPAenBm3JWTYmG5H83xzj2qj">
<button type="submit">Log out</button> -->

templates/search_results.html
<!-- templates/search_results.html -->
{% extends "base.html" %}
{% block content %}

<div class="col-md-8 mt-3 left">
    <h3 class="paddedhead coolhead">Search Results</h3>
    {% for Entry in entry_list %}
    <div class="papper mb-4">
        <div class="card-body text-center">
            <h2 class="card-title">{{ Entry.name|slice:":200" }}</h2>
            <p class="card-text text-muted h6">{{ Entry.author }} | {{ Entry.created_on}} </p>
            <p class="card-text">{{Entry.get_restype_display}}</p>
            <a href="{% url 'entry_detail' Entry.slug  %}" class="button">Read More &rarr;</a>
        </div>
    </div>
    {% endfor %}
</div>
{%endblock%}

templates/sidebar.html
{% block sidebar %}

<style>
    .card {
        width: 4000px;
        height: 254px;
        background: #f5f5f5;
        padding: 2rem 1.5rem;
        /* transition: box-shadow .3s ease, transform .2s ease; */
        border-radius: 10px;
    }

    .card-info {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        transition: transform .2s ease, opacity .2s ease;
    }

    /*Image*/
    .card-avatar {
        --size: 60px;
        background: linear-gradient(to top, #1b1b1b 0%, #d16b52 100%);
        width: var(--size);
        height: var(--size);
        border-radius: 50%;
        transition: transform .2s ease;
        margin-bottom: 1rem;
    }


    /*Card footer*/
    .card-social {
        transform: translateY(200%);
        display: flex;
        justify-content: space-around;
        width: 100%;
        opacity: 0;
        transition: transform .2s ease, opacity .2s ease;
    }

    .card-social__item {
        list-style: none;
    }

    .card-social__item svg {
        display: block;
        height: 18px;
        width: 18px;
        fill: #515F65;
        cursor: pointer;
        transition: fill 0.2s ease, transform 0.2s ease;
    }

    /*Text*/
    .card-title {
        color: #333;
        font-size: 1.5em;
        font-weight: 600;
        line-height: 2rem;
    }

    .card-subtitle {
        color: #859ba8;
        font-size: 0.8em;
    }

    /*Hover*/
    /* .card:hover {
        /* box-shadow: 0 8px 50px #23232333; */
    /* } */ 

    .card:hover .card-info {
        transform: translateY(-5%);
    }

    .card:hover .card-social {
        transform: translateY(100%);
        opacity: 1;
    }

    .card-social__item svg:hover {
        fill: #232323;
        transform: scale(1.1);
    }

    .card-avatar:hover {
        transform: scale(1.1);
    }
</style>

<!-- Sidebar Widgets Column -->
<!-- <div class="col-md-4 float-right "> -->
    <!-- <div class="card my-4"> -->
    <div class="card">
        <div class="card-info">
            <div class="card-avatar"></div>
            <div class="card-title">Contribute: </div>
            <div class="card-subtitle">Reach us out at:</div>
        </div>
        <ul class="card-social">
            <li class="card-social__item" >
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M14 9h3l-.375 3H14v9h-3.89v-9H8V9h2.11V6.984c0-1.312.327-2.304.984-2.976C11.75 3.336 12.844 3 14.375 3H17v3h-1.594c-.594 0-.976.094-1.148.281-.172.188-.258.5-.258.938V9z">
                    </path>
                </svg>
            </li>
            <li class="card-social__item">
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z">
                    </path>
                </svg>
            </li>
            <li class="card-social__item">
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z">
                    </path>
                </svg>
            </li>
        </ul>
    </div>
<!-- </div> -->
<!-- </div> -->
</div>

{% endblock sidebar %}